// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDQRvz8jLfShRWMLPSobA8a8Leb_FsDe8',
    appId: '1:422927221797:web:6b9e75cf5994a9ade9abcc',
    messagingSenderId: '422927221797',
    projectId: 'apna-vaidya',
    authDomain: 'apna-vaidya.firebaseapp.com',
    storageBucket: 'apna-vaidya.appspot.com',
    measurementId: 'G-BBBDGCZM1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArcvbjczznChm9Xrhu-A9ZeeC0xEOdi2c',
    appId: '1:422927221797:android:ec64f40e3647ad6fe9abcc',
    messagingSenderId: '422927221797',
    projectId: 'apna-vaidya',
    storageBucket: 'apna-vaidya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKNA9zrfQbrBa4auOE6q4OPcZy-e0iYU',
    appId: '1:422927221797:ios:d6fdce97ffd3be92e9abcc',
    messagingSenderId: '422927221797',
    projectId: 'apna-vaidya',
    storageBucket: 'apna-vaidya.appspot.com',
    iosBundleId: 'com.example.apnavaidyatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNKNA9zrfQbrBa4auOE6q4OPcZy-e0iYU',
    appId: '1:422927221797:ios:fdbe0dfbeef52e23e9abcc',
    messagingSenderId: '422927221797',
    projectId: 'apna-vaidya',
    storageBucket: 'apna-vaidya.appspot.com',
    iosBundleId: 'com.example.apnavaidyatest.RunnerTests',
  );
}
